### PR TITLE
Bug fix: Solves issue 12

### LINKED ISSUE #12: Exported Layer doesn't color based on score and Layer Title ignored
I exported a layer with these settings

image

The custom Layer Title I used was ignored and since I didn't specify a layer color I would expect the cells to be colored based on their score and the default color gradient.

### PR DESCRIPTION
**Pull request by jordanVoss**
Able to export files so that navigator will use default score coloring, Custom layer names are now used, hosting the data locally is now loaded, and README updated with corrected path for loading the dev extension.

Fixes #12 

## What Changed

* Fixed bug #12 by creating a checkbox to decide whether or not to use custom coloring. Additionally there was a bug where the default color was not being used when no color had been set for a bookmark
* Fixed exporting so that the layer name for navigator uses the custom layer name written by the user
* Fixed bug where, when running locally and accessing the web server, data was not being loaded into the browser
* Edited the README so it now tells you to point chrome to the 'public' folder when setting up the dev version of the extension

## Limitations

* None

### CODE REVIEW

File: src/BookmarksPanel.svelte [hunk 1]
```diff
@@ -32,11 +36,33 @@
         anchor.click();
         URL.revokeObjectURL(url);
     }
+
+    function updateColorSelection() {
+        // Toggle whether or not to change/export node colors
+        let cb = document.getElementById("color-toggle");
+
+        if (cb.checked === true) {
+            document.getElementById("color-selection").disabled = false;
```
Comment (mehaase) [inline src/BookmarksPanel.svelte:45]: Note that this only activates the first element on the page, so rows ≥2 are still disabled. See this example:

Screen Shot 2022-09-29 at 3 08 34 PM

Furthermore, try to avoid using `getElementById(...)` and other native DOM APIs. Use Svelte binding instead – see my comment below on the color input.

File: src/BookmarksPanel.svelte [hunk 2]
```diff
@@ -32,11 +36,33 @@
...
 </script>
 
 <BackButton on:back={() => dispatch("showSearch")} />
 <h2>ATT&CK Powered Suit</h2>
 <h3><i class="bi bi-bookmark-fill" /> Bookmarks</h3>
+<h3>
+    <input
+        type="checkbox"
+        id="color-toggle"
+        on:click={() => updateColorSelection()}
```
Comment (mehaase) [inline src/BookmarksPanel.svelte:62]: This can be simplified using Svelte binding. Instead of `on:click=...`, use `bind:checked={colorFlag}`. Then you can delete the body of `updateColorSelection()`..

File: src/BookmarksPanel.svelte [hunk 3]
```diff
@@ -74,6 +100,8 @@
                     ><input
                         type="color"
                         class="form-control color-picker"
+                        id="color-selection"
+                        disabled
```
Comment (mehaase) [inline src/BookmarksPanel.svelte:104]: Instead of setting disabled here and then using DOM APIs to toggle it, you can bind it's disabled state directly to colorFlag: `disabled={!colorFlag}`. So when colorFlag is true, its disabled state goes to false, i.e. enabled.

File: src/BookmarksPanel.svelte [hunk 4]
```diff
@@ -182,6 +210,12 @@
         margin: 0;
     }
 
+    .color-picker:disabled {
+        opacity: .25;
+    }
+
+
```
Comment (mehaase) [inline src/BookmarksPanel.svelte:217]: Please remove these extra lines.

File: src/attack.js [hunk 5]
```diff
@@ -56,16 +56,23 @@ export function getAttackUrl(text) {
  * @param {Array} techniques - Array of techniques to
  */
 export function buildAttackLayer(attackDomain, layerTitle, defaultColor,
-    techniques) {
+    techniques, colorFlag) {
     const layer = Object.assign({}, layerTemplate);
```
Comment (mehaase) [inline src/attack.js:60]: While reviewing this, I found another (pre-existing) bug. This `Object.assign()` line is supposed to copy the layerTemplate, but it's a shallow copy and not a deep copy. So when we append to the techniques, we're actually appending to whatever techniques we previously exported.

Since you're working on this code already, can you fix this? I can think of two quick solutions, one is to add a line after `Object.assign` that reinitializes techniques: `layer.techniques = []` -- hacky but gets the job done. 

The other quick solution is replace the `layerTemplate` global with a function that returns a layer template -- that way a new object is created each time. A little more work but less hacky.

**Review by mehaase — CHANGES_REQUESTED** [review]

**Comment by mehaase** [comment]
Thanks Jordan, this is looking good. I left a few requested changes on the code, and also want to iterate on the UX a bit as well:

1. Change the "Edit Color" checkbox. Move it down with the rest of the export controls, give it a more intuitive label, and change it to a popup menu. Choosing an option should show/hide the corresponding inputs in the table above. I made these mockups:

Screen Shot 2022-09-29 at 3 02 55 PM

When you select "Score", it hides the color inputs.

Screen Shot 2022-09-29 at 3 03 29 PM

When you select "Color" selector, it hides the scores.

2. We need to rethink how the default color works. I didn't give it much attention while building the v1.0 release, and it's not designed well. Even today i was confused about how it's supposed to work. I am in favor of removing it completely. But if we keep it, we need to rethink how it works and make it more obvious to the user what it does.

File: src/BookmarksPanel.svelte (hunk 3 above)
Comment (jordanVoss) [reply src/BookmarksPanel.svelte]: Removed disabled field since it is now controlled by whether or not the color column is showing.

File: src/attack.js (hunk 5 above)
Comment (jordanVoss) [reply src/attack.js]: I changed it to a function that returns the new layerTemplate in the same format as before, all of my testing shows that it solved the problem and only the shown bookmarks are exported.

**Review by mehaase — APPROVED** [review]
